name: 编译OpenWrt                 -       ophub/flippy-openwrt-actions

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
        
# 定时触发编译(每月1,16日早1点，北京时间-8小时)
#  schedule:
#    - cron: 1 16 1,16 * *
env:  
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - name: 准备完成
      uses: actions/checkout@main

    - name: Package OpenWrt Firmware
      uses: ophub/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: all
        KERNEL_VERSION_NAME: 6.1.y_6.6.y
        KERNEL_AUTO_LATEST: true
